IPD_IMGT_HLA_PROT = "https://github.com/ANHIG/IMGTHLA/raw/Latest/hla_prot.fasta"
IPD_MHC_PROT = "https://github.com/ANHIG/IPDMHC/raw/Latest/MHC_prot.fasta"
H2_CLASS_I_PROT = "https://raw.githubusercontent.com/histofyi/datasets/main/h2_prot.fasta"
HLA_CLASS_I = ["A","B","C","E","F","G"]
H2_CLASS_I = ["K","D","L"]
SEQUENCE_TYPES = ["cytoplasmic_sequences", "gdomain_sequences", "pocket_pseudosequences"]
IMGT_POCKET_RESIDUES = [7,9,24,45,59,62,63,66,67,69,70,73,74,76,77,80,81,84,95,97,99,114,116,118,143,147,150,152,156,158,159,163,167,171]

